### 1. IMPORTS

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.io.parquet import to_parquet
import pyarrow

print(pyarrow.__version__)

19.0.0

### 2. Load Data

In [4]:
sales = pd.read_csv("/Users/apple/Desktop/projects /FORECASTING/data/sales_train_evaluation.csv")
calendar = pd.read_csv("/Users/apple/Desktop/projects /FORECASTING/data/calendar.csv")
prices = pd.read_csv("/Users/apple/Desktop/projects /FORECASTING/data/sell_prices.csv")

In [5]:
print(f'Shape: {sales.shape}')
print(f'Rows: {sales.shape[0]:,} | Columns: {sales.shape[1]}')
sales .head()

Shape: (30490, 1947)
Rows: 30,490 | Columns: 1947

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

In [6]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1947 entries, id to d_1941
dtypes: int64(1941), object(6)
memory usage: 452.9+ MB

In [7]:
print(f'Shape: {calendar.shape}')
print(f'Rows: {calendar.shape[0]:,} | Columns: {calendar.shape[1]}')
calendar.head()

Shape: (1969, 14)
Rows: 1,969 | Columns: 14

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [8]:
calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   object
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   object
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   object
 7   event_name_1  162 non-null    object
 8   event_type_1  162 non-null    object
 9   event_name_2  5 non-null      object
 10  event_type_2  5 non-null      object
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), object(7)
memory usage: 215.5+ KB

In [9]:
print(f'Shape: {prices.shape}')
print(f'Rows: {prices.shape[0]:,} | Columns: {prices.shape[1]}')
prices.head()

Shape: (6841121, 4)
Rows: 6,841,121 | Columns: 4

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [10]:
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    object
 1   item_id     object
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 208.8+ MB

### 3. Missing Value

In [11]:
sales.isnull().sum()

id          0
item_id     0
dept_id     0
cat_id      0
store_id    0
           ..
d_1937      0
d_1938      0
d_1939      0
d_1940      0
d_1941      0
Length: 1947, dtype: int64

In [12]:
calendar.isnull().sum()

date               0
wm_yr_wk           0
weekday            0
wday               0
month              0
year               0
d                  0
event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
snap_CA            0
snap_TX            0
snap_WI            0
dtype: int64

In [13]:
prices.isnull().sum()

store_id      0
item_id       0
wm_yr_wk      0
sell_price    0
dtype: int64

In [14]:
event_cols = [
    "event_name_1",
    "event_name_2",
    "event_type_1",
    "event_type_2"
]

for col in event_cols:
    calendar[col] = calendar[col].fillna("No Event")

### 4. Data processing

In [15]:
sales_long = pd.melt(
    sales,
    id_vars=[
        "id",
        "item_id",
        "dept_id",
        "cat_id",
        "store_id",
        "state_id"
    ],
    var_name="d",
    value_name="sales"
)

In [16]:
sales.shape

(30490, 1947)

In [17]:
sales_long.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [18]:
sales_long["sales"].describe()

count    5.918109e+07
mean     1.130888e+00
std      3.870038e+00
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
max      7.630000e+02
Name: sales, dtype: float64

In [19]:
(sales_long["sales"] == 0).mean()

np.float64(0.6799776584040612)

In [20]:
df = sales_long.merge(calendar, on="d", how="left")

In [21]:
print(f'Shape: {df.shape}')
print(f'Rows: {df.shape[0]:,} | Columns: {df.shape[1]}')

Shape: (59181090, 21)
Rows: 59,181,090 | Columns: 21

In [23]:
cat_cols = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",
    "event_name_1",
    "event_name_2",
    "event_type_1",
    "event_type_2"
]

for col in cat_cols:
    df[col] = df[col].astype("category")

In [ ]:
df.to_parquet("/Users/apple/Desktop/projects /FORECASTING/data/processed/merged_data.parquet",engine="pyarrow",
    compression="snappy", index=False)

In [25]:
df.head()

,id,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,...,wday,month,year,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,No Event,No Event,No Event,No Event,0,0,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,No Event,No Event,No Event,No Event,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,No Event,No Event,No Event,No Event,0,0,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,No Event,No Event,No Event,No Event,0,0,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0,2011-01-29,11101,...,1,1,2011,No Event,No Event,No Event,No Event,0,0,0

In [26]:
df["date"] = pd.to_datetime(df["date"])

### 5. feature engineering

In [27]:
df["day"] = df["date"].dt.day
df["month"] = df["date"].dt.month
df["year"] = df["date"].dt.year
df["dayofweek"] = df["date"].dt.dayofweek
df["weekofyear"] = df["date"].dt.isocalendar().week.astype("int16")

In [28]:
df.drop(
    columns=[
        "weekday",
        "wday",
        "d"
    ],
    inplace=True
)

In [29]:
df = df.sort_values(["id", "date"])

df["lag_7"] = df.groupby("id")["sales"].shift(7)

df["lag_28"] = df.groupby("id")["sales"].shift(28)

KeyboardInterrupt:

In [ ]:
df.head(10)

,id,item_id,dept_id,cat_id,store_id,state_id,sales,date,wm_yr_wk,month,...,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,day,dayofweek,weekofyear,lag_7,lag_28
1612,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,3,2011-01-29,11101,1,...,No Event,No Event,0,0,0,29,5,4,NaN,NaN
32102,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2011-01-30,11101,1,...,No Event,No Event,0,0,0,30,6,4,NaN,NaN
62592,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2011-01-31,11101,1,...,No Event,No Event,0,0,0,31,0,5,NaN,NaN
93082,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,1,2011-02-01,11101,2,...,No Event,No Event,1,1,0,1,1,5,NaN,NaN
123572,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,4,2011-02-02,11101,2,...,No Event,No Event,1,0,1,2,2,5,NaN,NaN
154062,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,2,2011-02-03,11101,2,...,No Event,No Event,1,1,1,3,3,5,NaN,NaN
184552,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2011-02-04,11101,2,...,No Event,No Event,1,0,0,4,4,5,NaN,NaN
215042,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,2,2011-02-05,11102,2,...,No Event,No Event,1,1,1,5,5,5,3.0,NaN
245532,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2011-02-06,11102,2,...,No Event,No Event,1,1,1,6,6,5,0.0,NaN
276022,FOODS_1_001_CA_1_evaluation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2011-02-07,11102,2,...,No Event,No Event,1,1,0,7,0,6,0.0,NaN

In [ ]:
df.isna().sum()

id                   0
item_id              0
dept_id              0
cat_id               0
store_id             0
state_id             0
sales                0
date                 0
wm_yr_wk             0
month                0
year                 0
event_name_1         0
event_type_1         0
event_name_2         0
event_type_2         0
snap_CA              0
snap_TX              0
snap_WI              0
day                  0
dayofweek            0
weekofyear           0
lag_7           213430
lag_28          853720
dtype: int64

In [ ]:
df = df.dropna(subset=["lag_7", "lag_28"])

In [30]:
df["rolling_mean_7"] = (
    df.groupby("id")["sales"]
      .transform(lambda x: x.shift(1).rolling(7).mean())
)
df["rolling_mean_28"] = (
    df.groupby("id")["sales"]
      .transform(lambda x: x.shift(1).rolling(28).mean())
)

/var/folders/yz/g64y8mmn14s9pwtfnjw85rlc0000gn/T/ipykernel_24571/4004087539.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("id")["sales"]
/var/folders/yz/g64y8mmn14s9pwtfnjw85rlc0000gn/T/ipykernel_24571/4004087539.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("id")["sales"]

In [31]:
df[[ "rolling_mean_7", "rolling_mean_28"]].isna().sum()

rolling_mean_7     213430
rolling_mean_28    853720
dtype: int64

In [32]:
df = df.dropna(
    subset=[
        "rolling_mean_7",
        "rolling_mean_28"
    ]
)

In [33]:
df.shape

(58327370, 23)